"""entrants_groups.created_at

Revision ID: 56e978fcf807
Revises: 0f89554abc32
Create Date: 2026-05-16 18:33:06.953900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56e978fcf807'
down_revision: Union[str, Sequence[str], None] = '0f89554abc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrants_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrants_groups', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
