"""empty message

Revision ID: 641d02bb9297
Revises: e2a5c9d14b7f
Create Date: 2026-07-01 11:58:28.892492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641d02bb9297'
down_revision: Union[str, Sequence[str], None] = 'e2a5c9d14b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_campaigns_specialties', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'specialties', ['id_speciality'], ['id'])

    with op.batch_alter_table('rating_entries', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'specialties', ['id_speciality'], ['id'])

    with op.batch_alter_table('specialties_entrants', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'specialties', ['id_speciality'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties_entrants', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('rating_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('admission_campaigns_specialties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
