"""DK-36 application_statuses.is_default

Revision ID: 68b699f7abfc
Revises: 7b30051fe9f0
Create Date: 2026-06-29 23:44:03.675315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '68b699f7abfc'
down_revision: Union[str, Sequence[str], None] = '7b30051fe9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_statuses', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
