"""specialties.educational_and_professional_program nullable

Revision ID: abb408229692
Revises: da3a7e4d2381
Create Date: 2026-05-16 11:52:15.374351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb408229692'
down_revision: Union[str, Sequence[str], None] = 'da3a7e4d2381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('id_entry_base',
               nullable=False)

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('educational_and_professional_program',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('educational_and_professional_program',
               nullable=False)

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('id_entry_base',
               nullable=True)

    # ### end Alembic commands ###
