"""empty message

Revision ID: d102644d06c2
Revises: 
Create Date: 2026-04-30 08:14:20.100553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd102644d06c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('application_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrants_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_document_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_zno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kinship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_of_funding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_conditions',
    sa.Column('subcategory_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_kvota', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('subcategory_code')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pib', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_worker'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('entrants_exams',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_item_zno', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['entrants_groups.id'], ),
    sa.ForeignKeyConstraint(['id_item_zno'], ['item_zno.id'], ),
    sa.PrimaryKeyConstraint('id_group', 'id_item_zno')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edbo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pib', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citizenship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_of_registration_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('place_of_registration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mokpp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('the_need_for_a_dormitory', sa.Boolean(), nullable=False),
    sa.Column('id_source_of_funding', sa.Integer(), nullable=False),
    sa.Column('entry_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_source_of_funding'], ['source_of_funding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_actions',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id_role', 'id_action')
    )
    op.create_table('specialties',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('educational_and_professional_program', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_department'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('code', 'id_department')
    )
    op.create_table('workers_actions',
    sa.Column('id_worker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_action'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id_worker', 'id_action')
    )
    op.create_table('workers_roles',
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['id_worker'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id_worker', 'id_role')
    )
    op.create_table('document_about_education',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('title', 'number')
    )
    op.create_table('entrants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_application_status', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['id_application_status'], ['application_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_document',
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['identity_document_type.id'], ),
    sa.PrimaryKeyConstraint('number', 'id_type')
    )
    op.create_table('information_about_relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_kinship', sa.Integer(), nullable=False),
    sa.Column('pib', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_kinship'], ['kinship.id'], ),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('military_accounting',
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('number', 'series')
    )
    op.create_table('results_zno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_items_zno', sa.Integer(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_items_zno'], ['item_zno.id'], ),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_conditions_person',
    sa.Column('id_person', sa.Integer(), nullable=False),
    sa.Column('id_special_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_of_issue', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['id_person'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['id_special_condition'], ['special_conditions.subcategory_code'], ),
    sa.PrimaryKeyConstraint('id_person', 'id_special_condition')
    )
    op.create_table('specialties_entrants',
    sa.Column('id_entrant', sa.Integer(), nullable=False),
    sa.Column('id_specialties', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_entrant'], ['entrants.id'], ),
    sa.ForeignKeyConstraint(['id_specialties'], ['specialties.code'], ),
    sa.PrimaryKeyConstraint('id_entrant', 'id_specialties')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialties_entrants')
    op.drop_table('special_conditions_person')
    op.drop_table('results_zno')
    op.drop_table('military_accounting')
    op.drop_table('medical_reference')
    op.drop_table('information_about_relatives')
    op.drop_table('identity_document')
    op.drop_table('entrants')
    op.drop_table('document_about_education')
    op.drop_table('workers_roles')
    op.drop_table('workers_actions')
    op.drop_table('specialties')
    op.drop_table('roles_actions')
    op.drop_table('persons')
    op.drop_table('entrants_exams')
    op.drop_table('auth_tokens')
    op.drop_table('workers')
    op.drop_table('special_conditions')
    op.drop_table('source_of_funding')
    op.drop_table('roles')
    op.drop_table('kinship')
    op.drop_table('item_zno')
    op.drop_table('identity_document_type')
    op.drop_table('entrants_groups')
    op.drop_table('departments')
    op.drop_table('application_statuses')
    op.drop_table('actions')
    # ### end Alembic commands ###
