"""DK-1 entrants schema: photo blob, entry_base lookup, entrant_group fk

Revision ID: da3a7e4d2381
Revises: bf21db00fd25
Create Date: 2026-05-16 11:21:13.000852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'da3a7e4d2381'
down_revision: Union[str, Sequence[str], None] = 'bf21db00fd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adjusted from autogenerated output:
    - persons.photo: drop old TEXT column and recreate as BLOB (LargeBinary).
    - persons.id_entry_base: created as nullable=True since persons may already exist;
      callers must populate before relying on it. Safe here because table is empty.
    """
    op.create_table('entry_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_entrant_group', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_entrants_id_entrant_group', 'entrants_groups', ['id_entrant_group'], ['id'])

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('photo')
        batch_op.add_column(sa.Column('photo', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('photo_mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('id_entry_base', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_persons_id_entry_base', 'entry_base', ['id_entry_base'], ['id'])
        batch_op.drop_column('entry_base')


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_base', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_persons_id_entry_base', type_='foreignkey')
        batch_op.drop_column('id_entry_base')
        batch_op.drop_column('photo_mime_type')
        batch_op.drop_column('photo')
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('entrants', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entrants_id_entrant_group', type_='foreignkey')
        batch_op.drop_column('id_entrant_group')

    op.drop_table('entry_base')
