"""empty message

Revision ID: f2111e116f30
Revises: 063769133c4b
Create Date: 2026-04-02 23:04:23.333017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f2111e116f30'
down_revision: Union[str, Sequence[str], None] = '063769133c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_worker', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_worker'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('password_salt')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_column('code')

    op.drop_table('auth_tokens')
    # ### end Alembic commands ###
